import Head from "next/head";
import Link from "next/link";

import { useStateContext } from "@/context/ContextProvider";

export default function Profile() {
    const { user } = useStateContext();

    return (
        <>
            <Head>
                <title>
                    {user?.displayName || user?.email} customer profile | Benji
                    Bakes
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <Link href="/">
                    <a>Back to home</a>
                </Link>
                <div>{user?.displayName}</div>
                <div>{user?.email}</div>
            </div>
            {/* {paymentIntents.data.length && ( */}
            {/* <div> */}
            {/* Previous Orders */}
            {/* {paymentIntents.data.map(async (intent, i) => {})} */}
            {/* // Retrieve line items
                        // console.log({ intent });
                        // const body = {
                        //     pi_id: intent.id,
                        // }; */}
            {/* // const res = await fetch(
                        //     `${process.env.NEXT_PUBLIC_API_URL}/sessions`,
                        //     {
                        //         method: "POST",
                        //         body: JSON.stringify(body),
                        //         headers: {
                        //             "Content-Type": "application/json",
                        //         },
                        //     }
                        // ); */}
            {/* // const items = await res.json(); // console.log({items});
                    // return ( //{" "}
                    <div key={i}>
                        // <div>Status: {intent.status}</div>
                        //{" "}
                        <div>
                            // <div>Amount: {intent.amount}</div>
                            //{" "}
                        </div>
                        //{" "}
                    </div>
                    // ); // })} */}
        </>
    );
}
export async function getServerSideProps(context) {
    console.log(context.req.cookies);
    // const router = useRouter();
    // console.log(context.params.id);
    // const checkoutSession = await retrieveCheckoutSession(context.params.id);
    // if (!checkoutSession) {
    //     router.push("/");
    // }
    // const id = cookies.get("customer");
    // const serverCookies = new Cookies(context.req.cookies);
    // const customerCookies = await serverCookies.get("customer");
    // console.log({ customerCookies });

    // const customer = await retrieveCustomer(customerCookies.id);
    // const paymentIntents = await retrievePaymentIntents(customerCookies.id);
    // const charges = await retrieveCharges(customerCookies.id);

    return {
        props: {
            // customer,
            // paymentIntents,
            // charges,
        }, // will be passed to the page component as props
    };
}
