import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Colors() {
    return (
        <div className="">
            <Head>
                <title>Benji Bakes Colors</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <div className="bg-brown-50 py-20"></div>
                <div className="bg-brown-900 py-20"></div>
                <div className="bg-amber-50 py-20"></div>
                <div className="bg-amber-900 py-20"></div>
                <div className="bg-yellow-50 py-20"></div>
                <div className="bg-yellow-900 py-20"></div>
            </main>
        </div>
    );
}
